# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jacob/VendingMachine/VendingMachine.cache/wt [current_project]
set_property parent.project_path C:/Users/jacob/VendingMachine/VendingMachine.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/jacob/VendingMachine/VendingMachine.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/jacob/VendingMachine/VendingMachine.srcs/sources_1/new/7segmentdisplay.vhd
  C:/Users/jacob/VendingMachine/VendingMachine.srcs/sources_1/new/KYPD.vhd
  C:/Users/jacob/VendingMachine/VendingMachine.srcs/sources_1/new/Machine.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Machine -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Machine.dcp

catch { report_utilization -file Machine_utilization_synth.rpt -pb Machine_utilization_synth.pb }
